spring.application.name=ChatApp
#Para configurar o url ->  jdbc:postgresql://localhost:[numero da porta]/[nome do servidor]

spring.datasource.url=jdbc:postgresql://localhost:5432,localhost:5433/[nome do seu banco]?targetServerType=primary&loadBalanceHosts=false
spring.datasource.username=[nome do seu banco
spring.datasource.password=[senha do seu banco]
spring.jpa.hibernate.ddl-auto = update

server.port=${PORT:8081}

# Mostra quando o Hikari cria ou remove conexões
logging.level.com.zaxxer.hikari=DEBUG
# Opcional: Mostra mensagens detalhadas do driver do Postgres
logging.level.org.postgresql=INFO

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Aumentar capacidade do Tomcat (Threads para processar Login e WebSockets)
server.tomcat.threads.max=500
server.tomcat.threads.min-spare=50
server.tomcat.accept-count=1000

# Otimizar Pool de Conexões do Banco de Dados (HikariCP)
# Reduzido para 15 para evitar estourar o limite do Postgres (100) com 5 instâncias
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5

# Aumentar concorrência do RabbitMQ (Múltiplos "workers" para salvar mensagens)
spring.rabbitmq.listener.simple.concurrency=5
spring.rabbitmq.listener.simple.max-concurrency=10
spring.rabbitmq.listener.simple.prefetch=20
